### ISSUE TITLE
请问能显示光标吗

### ISSUE THREAD

**Issue by louyulin** [Airsaid/InputCodeLayout#2]

**Comment by Airsaid** [comment]
目前不支持光标，不过可以支持。如果需要支持的话我会在下一版本中更新。

**Comment by louyulin** [comment]
谢谢 如果能加上对我是极大的帮助 如果我自己加的话 能指点一下在哪做修改吗

**Comment by louyulin** [comment]
你好 在源码里找到了   mEdtCode.setCursorVisible(true); 嘿嘿

**Comment by Airsaid** [comment]
好的，既然你已经解决，那我就先关掉该 issue 了。
